---
title: "Logistic Classification"
description: |
  This post serves as a discussion board for the third tab
  in the ML4PP course: Supervised Classification: Logistic Regression.

preview: LogitpythonR.png
categories:
    - Prediction
    - Policy
    - Logistic Regression
    - Classification
    - R
    - Python
author:
    - name: Michelle González Amador
      affiliation: UNU-MERIT and Maastricht University
      orcid_id: 0000-0003-0265-4545
base_url: https://ml4pp-blog.com/
output:
  distill::distill_article:
    self_contained: false
citation: false
rss:
  full_content: true
---

## Overview

In the [Classification:Logistic](https://www.ml4publicpolicy.com/classification.html) tab of the ML4PP site, Stephan introduced us to a simple binary classification algorithm: the logistic regression. In the previous session, we hinted at the possibility of improving our prediction model. Based on the results of a binary prediction - an individual in Malawi is considered poor if they ball on or below some income threshold - using a logistic regression, we have indeed marginally improved our prediction abilities. Although a simple algorithm, do not underestimate the predictive power of a logistic regression! Complex social problems can sometimes be aided by simple tools. Besides our targeting project (we're in it for the long haul! ... or until we have reached a point where we can no longer improve our predictions), another interesting social good problem that has been tackled by a logistic regression is that of [Predicting Micronutrient Deficiency](https://onlinelibrary.wiley.com/doi/10.1002/aaai.12080) by Elizabeth Bondi-Kelly and friends. Their (logistic) model, which uses satellite imagery, is accurate and outperforms more traditional survey methods. Being able to predict regions that are at risk of malnutrition is key for Health Policymakers to make informed decisions about when and where to allocate vitamins, supplements, or other resources to combat or even prevent it.  


Please feel free to leave a comment here if you have any questions about binary classification models, in particular a logistic regression model, and how to assess its performance using R or Python. As always, you can also leave a comment to suggest a date to meet up in [Gather.Town](https://app.gather.town/app/oHbUVQSaCs7SOToI/ML%20for%20Public%20Policy) with other people so you can chat in real time!

Happy coding, everyone! 